### ISSUE TITLE
Missing `references.bib` and `txex-bar`

### ISSUE THREAD

**Issue by mahrud** [favonia/hdtt2020-notes#3]
1. `references.bib`, referenced in `hdtt2020.sty` and presumably including the reference to `hott-as:book`, is missing.

2. I ran into an issue where the `latex` command worked fine, but `pdflatex` complained at a certain `txex-bar` file being missing:
```
kpathsea: Running mktextfm txex-bar
/usr/share/texlive/texmf-dist/web2c/mktexnam: Could not map source abbreviation  for txex-bar.
/usr/share/texlive/texmf-dist/web2c/mktexnam: Need to update ?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input txex-bar
This is METAFONT, Version 2.7182818 (TeX Live 2018) (preloaded base=mf)


kpathsea: Running mktexmf txex-bar
! I can't find file `txex-bar'.
```

In case anyone else has this issue, the solution was to install the `newtx` package (i.e., in addition to `newpx`).

**Comment by favonia** [comment]
Thanks!

1. The missing `references.bib` was fixed by #2. Sorry that I forgot to upload it.
2. This is interesting. I thought we are only using `newpx`. (I have both installed already.) :-/
